using Scanner111.Common.Models.Reporting;

namespace Scanner111.Common.Services.Reporting;

/// <summary>
/// Provides fluent API for building crash log analysis reports from fragments.
/// </summary>
public interface IReportBuilder
{
    /// <summary>
    /// Adds a report fragment to the builder.
    /// </summary>
    /// <param name="fragment">The fragment to add. Empty fragments are ignored.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IReportBuilder Add(ReportFragment fragment);

    /// <summary>
    /// Conditionally adds content generated by a function, with an optional header.
    /// </summary>
    /// <param name="contentGenerator">Function that generates the content. Only called if needed.</param>
    /// <param name="header">Optional header to prepend to the content.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IReportBuilder AddConditional(Func<ReportFragment> contentGenerator, string? header = null);

    /// <summary>
    /// Adds a section with a name and lines of content.
    /// </summary>
    /// <param name="sectionName">The name of the section (used as header).</param>
    /// <param name="lines">The lines of content for the section.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IReportBuilder AddSection(string sectionName, IEnumerable<string> lines);

    /// <summary>
    /// Builds and returns the final composed report fragment.
    /// </summary>
    /// <returns>The composed report fragment containing all added content.</returns>
    ReportFragment Build();
}
