using Scanner111.Common.Models.Analysis;
using Scanner111.Common.Models.Reporting;

namespace Scanner111.Common.Services.Reporting;

/// <summary>
/// Provides standard report section generators for crash log analysis.
/// </summary>
public static class ReportSections
{
    /// <summary>
    /// Creates a standard report header with crash information.
    /// </summary>
    /// <param name="header">The crash header containing version and error information.</param>
    /// <param name="gameName">The name of the game (e.g., "Fallout 4").</param>
    /// <returns>A report fragment containing the formatted header.</returns>
    public static ReportFragment CreateHeader(CrashHeader header, string gameName)
    {
        var lines = new List<string>
        {
            $"# Crash Log Analysis - {gameName}",
            $"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}",
            string.Empty,
            $"**Game Version**: {header.GameVersion}",
            $"**Crash Generator**: {header.CrashGeneratorVersion}",
            $"**Error**: {header.MainError}"
        };

        if (header.CrashTimestamp.HasValue)
        {
            lines.Add($"**Crash Time**: {header.CrashTimestamp.Value:yyyy-MM-dd HH:mm:ss}");
        }

        lines.Add(string.Empty);

        return ReportFragment.FromLines(lines.ToArray());
    }

    /// <summary>
    /// Creates a plugin summary section showing plugin counts and potential issues.
    /// </summary>
    /// <param name="plugins">The list of detected plugins.</param>
    /// <returns>A report fragment containing the plugin summary.</returns>
    public static ReportFragment CreatePluginSummary(IReadOnlyList<PluginInfo> plugins)
    {
        if (plugins.Count == 0)
        {
            return new ReportFragment();
        }

        var fullPlugins = plugins.Count(p => !p.IsLightPlugin);
        var lightPlugins = plugins.Count(p => p.IsLightPlugin);

        var lines = new List<string>
        {
            "## Plugin Summary",
            string.Empty,
            $"- **Total Plugins**: {plugins.Count}",
            $"- **Full Plugins**: {fullPlugins} / 254",
            $"- **Light Plugins (ESL)**: {lightPlugins} / 4096",
            string.Empty
        };

        // Add warnings if approaching limits
        if (fullPlugins >= 240)
        {
            lines.Add($"⚠️ **Warning**: Approaching full plugin limit ({fullPlugins}/254)");
            lines.Add(string.Empty);
        }

        if (lightPlugins >= 3900)
        {
            lines.Add($"⚠️ **Warning**: Approaching light plugin limit ({lightPlugins}/4096)");
            lines.Add(string.Empty);
        }

        return ReportFragment.FromLines(lines.ToArray());
    }

    /// <summary>
    /// Creates a warnings section from a list of warning messages.
    /// </summary>
    /// <param name="warnings">The list of warnings to include.</param>
    /// <returns>A report fragment containing the warnings, or empty if no warnings.</returns>
    public static ReportFragment CreateWarningsSection(IReadOnlyList<string> warnings)
    {
        if (warnings.Count == 0)
        {
            return new ReportFragment();
        }

        var lines = new List<string>
        {
            "## Warnings",
            string.Empty
        };

        foreach (var warning in warnings)
        {
            lines.Add($"⚠️ {warning}");
        }

        lines.Add(string.Empty);

        return ReportFragment.FromLines(lines.ToArray());
    }

    /// <summary>
    /// Creates a recommendations section from a list of recommended actions.
    /// </summary>
    /// <param name="recommendations">The list of recommendations.</param>
    /// <returns>A report fragment containing the recommendations, or empty if none.</returns>
    public static ReportFragment CreateRecommendationsSection(IReadOnlyList<string> recommendations)
    {
        if (recommendations.Count == 0)
        {
            return new ReportFragment();
        }

        var lines = new List<string>
        {
            "## Recommended Actions",
            string.Empty
        };

        for (int i = 0; i < recommendations.Count; i++)
        {
            lines.Add($"{i + 1}. {recommendations[i]}");
        }

        lines.Add(string.Empty);

        return ReportFragment.FromLines(lines.ToArray());
    }

    /// <summary>
    /// Creates a footer section with additional information and links.
    /// </summary>
    /// <returns>A report fragment containing the standard footer.</returns>
    public static ReportFragment CreateFooter()
    {
        var lines = new[]
        {
            "---",
            string.Empty,
            "*This report was automatically generated by Scanner111*",
            string.Empty,
            "For more information on crash log analysis:",
            "- [Crash Log Reading 101](https://www.nexusmods.com/fallout4/articles/3115)",
            "- [Common Crash Causes](https://www.nexusmods.com/fallout4/articles/3769)",
            string.Empty
        };

        return ReportFragment.FromLines(lines);
    }
}
